[package]
name = "AoC2020"
version = "0.1.0"
authors = ["Stella Cannefax <stella@fakemail.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
